# Generated by Django 3.1.6 on 2021-04-05 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('name', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True)),
                ('short_name', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('logo', models.ImageField(null=True, upload_to='')),
                ('url', models.URLField(blank=True, null=True)),
                ('subject_areas', models.TextField(max_length=200)),
                ('expected_submissions', models.IntegerField(blank=True)),
                ('is_valid', models.BooleanField()),
                ('ca', models.ManyToManyField(related_name='ca', to='accounts.User')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='create_by', to='accounts.user')),
            ],
        ),
    ]
