# Generated by Django 3.1.6 on 2021-04-07 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('name', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True)),
                ('short_name', models.CharField(blank=True, max_length=125)),
                ('location', models.CharField(blank=True, max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('ca_emails', models.TextField(blank=True)),
                ('start_date', models.DateTimeField(null=True)),
                ('paper_submission_deadline', models.DateTimeField(null=True)),
                ('review_submission_deadline', models.DateTimeField(null=True)),
                ('cam_pos_submission_deadline', models.DateTimeField(null=True)),
                ('end_date', models.DateTimeField(null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='')),
                ('url', models.URLField(blank=True, null=True)),
                ('subject_areas', models.TextField(max_length=200)),
                ('expected_submissions', models.IntegerField(blank=True, null=True)),
                ('is_valid', models.BooleanField(default=False)),
                ('ACM_conference_confirmation', models.BooleanField(default=False)),
                ('ca', models.ManyToManyField(related_name='ca', to='accounts.User')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to='accounts.user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('name', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True)),
                ('short_name', models.CharField(blank=True, max_length=125)),
                ('location', models.CharField(blank=True, max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('ca_emails', models.TextField(blank=True)),
                ('start_date', models.DateTimeField(null=True)),
                ('paper_submission_deadline', models.DateTimeField(null=True)),
                ('review_submission_deadline', models.DateTimeField(null=True)),
                ('cam_pos_submission_deadline', models.DateTimeField(null=True)),
                ('end_date', models.DateTimeField(null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='')),
                ('url', models.URLField(blank=True, null=True)),
                ('subject_areas', models.TextField(max_length=200)),
                ('expected_submissions', models.IntegerField(blank=True, null=True)),
                ('is_valid', models.BooleanField(default=False)),
                ('ACM_conference_confirmation', models.BooleanField(default=False)),
                ('parent_conference_name', models.CharField(max_length=250)),
                ('ca', models.ManyToManyField(related_name='workshop_ca', to='accounts.User')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workshop_created_by', to='accounts.user')),
                ('parent_conference', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='conference.conference')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
