# Generated by Django 3.1.6 on 2021-04-06 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='ACM_conference_confirmation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='conference',
            name='ca_emails',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='conference',
            name='cam_pos_submission_deadline',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='conference',
            name='paper_submission_deadline',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='conference',
            name='review_submission_deadline',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='conference',
            name='end_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='conference',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='conference',
            name='short_name',
            field=models.CharField(blank=True, max_length=125),
        ),
        migrations.AlterField(
            model_name='conference',
            name='start_date',
            field=models.DateTimeField(null=True),
        ),
    ]
