# Generated by Django 3.1.6 on 2021-04-06 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0003_auto_20210406_0821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference',
            name='expected_submissions',
            field=models.IntegerField(null=True),
        ),
    ]
