# Generated by Django 3.1.6 on 2021-04-06 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0005_auto_20210406_0825'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='location',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='conference',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
