# Generated by Django 3.1.6 on 2021-04-13 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gsp', '0002_auto_20210413_1110'),
        ('reviewer', '0002_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='paper_submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gsp.papersubmission'),
        ),
    ]
