# Generated by Django 3.1.2 on 2021-04-14 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conference', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaperSubmission',
            fields=[
                ('title', models.CharField(blank=True, max_length=50, primary_key=True, serialize=False)),
                ('abstract', models.TextField()),
                ('pdf_paper', models.FileField(upload_to='tmp/cms-project/main_paper')),
                ('supplementary_material', models.FileField(blank=True, default=None, null=True, upload_to='tmp/cms-project/supplementary')),
                ('author_list', models.TextField()),
                ('conference', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='conference.conference')),
                ('main_author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CamPosSubmission',
            fields=[
                ('title', models.CharField(blank=True, max_length=50, primary_key=True, serialize=False)),
                ('camera_ready_pdf', models.FileField(upload_to='tmp/cms-project/camera')),
                ('poster_pdf', models.FileField(upload_to='tmp/cms-project/posters')),
                ('conference', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='conference.conference')),
                ('main_author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AuthorResponseSubmission',
            fields=[
                ('title', models.CharField(blank=True, max_length=50, primary_key=True, serialize=False)),
                ('response_pdf', models.FileField(blank=True, null=True, upload_to='tmp/cms-project/responses')),
                ('conference', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='conference.conference')),
                ('main_author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.user')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
