# Generated by Django 3.1.2 on 2021-04-12 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorResponseSubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_pdf', models.FileField(blank=True, null=True, upload_to='tmp/cms-project/responses')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CamPosSubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera_ready_pdf', models.FileField(upload_to='tmp/cms-project/camera')),
                ('poster_pdf', models.FileField(upload_to='tmp/cms-project/posters')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PaperSubmission',
            fields=[
                ('title', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('abstract', models.TextField()),
                ('pdf_paper', models.FileField(upload_to='tmp/cms-project/main_paper')),
                ('supplementary_material', models.FileField(blank=True, default=None, null=True, upload_to='tmp/cms-project/supplementary')),
                ('author_list', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
