# Generated by Django 3.1.2 on 2021-04-13 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0001_initial'),
        ('accounts', '0002_researchprofile'),
        ('gsp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuthorResponseSubmission',
        ),
        migrations.DeleteModel(
            name='CamPosSubmission',
        ),
        migrations.AddField(
            model_name='papersubmission',
            name='conference',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='conference.conference'),
        ),
        migrations.AddField(
            model_name='papersubmission',
            name='main_author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.user'),
        ),
    ]
