# Generated by Django 3.1.6 on 2021-04-13 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_researchprofile'),
        ('conference', '0001_initial'),
        ('gsp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authorresponsesubmission',
            name='id',
        ),
        migrations.RemoveField(
            model_name='campossubmission',
            name='id',
        ),
        migrations.AddField(
            model_name='authorresponsesubmission',
            name='conference',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='conference.conference'),
        ),
        migrations.AddField(
            model_name='authorresponsesubmission',
            name='main_author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.user'),
        ),
        migrations.AddField(
            model_name='authorresponsesubmission',
            name='title',
            field=models.CharField(blank=True, max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='campossubmission',
            name='conference',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='conference.conference'),
        ),
        migrations.AddField(
            model_name='campossubmission',
            name='main_author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.user'),
        ),
        migrations.AddField(
            model_name='campossubmission',
            name='title',
            field=models.CharField(blank=True, max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='papersubmission',
            name='conference',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='conference.conference'),
        ),
        migrations.AddField(
            model_name='papersubmission',
            name='main_author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.user'),
        ),
        migrations.AlterField(
            model_name='papersubmission',
            name='title',
            field=models.CharField(blank=True, max_length=50, primary_key=True, serialize=False),
        ),
    ]
