# Generated by Django 3.1.2 on 2021-04-14 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gsp', '0002_auto_20210413_1110'),
        ('gsp', '0002_auto_20210413_1135'),
    ]

    operations = [
    ]
