# Generated by Django 2.1 on 2021-04-18 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gsp', '0001_initial'),
        ('conference', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaChair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conference.Conference')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.User')),
            ],
        ),
        migrations.CreateModel(
            name='AssignedAreaChairs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_chair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='area_chair.AreaChair')),
                ('paper_submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gsp.PaperSubmission')),
            ],
        ),
    ]
